# fly.toml app configuration file generated for car-minder-backend on 2023-06-02T20:46:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "car-minder-backend"
primary_region = "scl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
